In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [4]:
data = np.array(http://localhost:8888/notebooks/numpy/vectors%2C%20matrices%20and%20multidimensional%20arrays.ipynb#[[1,2],[3,4],[5,6]])
# metadata about the numpy array
print(data.ndim)
print(data.size)
print(data.dtype)
print(data.nbytes)

2
6
int64
48


In [6]:
# generate array of a partivular data type
np.array([2,3,4], dtype=np.complex)

array([2.+0.j, 3.+0.j, 4.+0.j])

In [1]:
def f(x):
    y = np.ones_like(x)
    return y

In [5]:
f(6)

array(1)

In [11]:
# fancy indexing and boolean valued indexing
# with fancy indexing an array can be indexed by nother array, list or a sequence
# of integers whose values select elements in the indexed array

arr = np.random.normal(size=10)
arr[arr>1.5]

array([2.04296925])

In [12]:
# an n dimensional array can be flattened into 1 dimensional arrau using flatten and ravel
# new axis or column can be added as well

data = np.arange(0, 5)
column = data[:, np.newaxis]

In [20]:
# examples
# representation of problems in linear algebra
# suppose the price of a ball and 2 balts or 2 balls and a bat is 100,
# we need to find the price of each

# translate the problem into mathematical form
# 2x + y = 100
# x + 2y = 100

# in linear algebra data is represented in the form of linear equations,
# these linear equations sre in turn represented in the form of matrices and 
# vectors

#visualize the problem
# solve the problem using elementary algebraic operations.
# possible methods ..
    # Elimination / Substitution, Cramers Rule, Row reduction, Matrix Solution
    
#Matrix method
#in Matrix method the system to be solved is represented in the form of AX =B
#So we can translate it into
A = np.array([[2, 1],
     [1, 2]
    ])
# X = [[x],
#      [y]
#     ]
B = np.array([[20],
     [26]
    ])
# to find the values of x and Y, we need to find the values of in the Matrix X
# to do so we can take a dot product of the inverse of matrix A and Matrix B
inv_A = np.linalg.inv(A)
X = inv_A.dot(B)
X

array([[ 4.66666667],
       [10.66666667]])

In [21]:
# Example 2
# 4x + 3y  20
# -5x + 9y = 26

A = np.array([
    [4, 3],
    [-5, 9]
])

# X = np.array([
#     [x],
#     [y]
# ])

B = np.array([
    [20],
    [26]
])

# since AX = B, X = A inverse dot B
X = np.linalg.inv(A).dot(B)
X

array([[2.],
       [4.]])

In [23]:
# Example 3
# 4x + 3y + 2z = 25
# -2x + 2y + 3z = -10
# 3x -5y + 2z = -4

A = np.array([
    [4, 3, 2],
    [-2, 2, 3],
    [3, -5, 3]
])

B = np.array([
    [25],
    [-10],
    [-4]
])

X = np.linalg.inv(A).dot(B)
#or
np.linalg.solve(A, B)

array([[ 5.0729927 ],
       [ 2.76642336],
       [-1.79562044]])

In [24]:
# real World example
"""
Suppose, a fruit-seller sold 20 mangoes and 10 oranges in one day for a total of $350. The next day he sold 17 mangoes and 22 oranges for $500. If the prices of the fruits remained unchanged on both the days, what was the price of one mango and one orange?
"""

# 20x + 10y = 350
# 17x + 22y = 500

A = np.array([[20, 10], [17, 22]])
B = np.array([350, 500])
X = np.linalg.solve(A,B)

In [25]:
# creating arrays
# np.array - creates an array for which elements are given by an array-like object
#  nested python list, a tuple, an iterable sequence, or another ndarray instance

# np.zeros(ones) - creates an array with specified dimensions and data type that is filled with zeros(ones)
# np.diag - creates an array with specified values as diagonal and zeros elsewhere
# np.arange - creates an array with evenly spaced values between the specified start, step and end
# np.linspace - creates an array with evenly spaced values between start and end values using specified number or elements
# np.logspace - creates an array with values that are logarithimically spaced between given start and end values
# np,meshgrid - generates coordinate matrices and higher order-dimensional coordinate arrays from one dimensional coodinate vectors

np.logspace(0, 2, 5) # 5 data points between 10^1 to 10^2


array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [26]:
# Meshgrid arrays
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [27]:
# Multi dimensional arrays
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6,6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [29]:
# Solving linear systems
# A linear system of equations s a collection of equations
# way of solving.. 
# 1. Gaussian Elimination - perform Row operations to reduce the system to its acheleon form and then solve
 # examples of row operations
#     Add  times row  to row .
# Multiply row  by scalar .
# Switch rows  and .

A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
# Each of the elementary row operations is the result of matrix multiplication by an elementary matrix (on the left). To add  times row  to row  in a matrix , we multiply  by the matrix  where  is equal to the identity matrix except the  entry is . For example, if  is 3 by 3 and we want to add 3 times row 2 to row 0 (using 0 indexing) then
E1 = np.array([[1, 0, 3], [0, 1, 0], [0, 0, 1]])

In [30]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])

In [32]:
# To multiply  times row  in a matrix , we multiply  by the matrix  where  is equal to the identity matrix except the  entry is . For example, if  is 3 by 3 and we want to multiply row 1 by -2 then
E2 = np.array([[1, 0, 0], [0, -2, 0], [0, 0, 1]])
E2 @ A

array([[ 1,  1,  2],
       [ 2, -6, -2],
       [ 0,  5,  2]])

In [33]:
# To multiply  times row  in a matrix , we multiply  by the matrix  where  is equal to the identity matrix except the  entry is . For example, if  is 3 by 3 and we want to multiply row 1 by -2 then
E3 = np.array([[1,0,0],[0,0,1],[0,1,0]])
E3 @ A

array([[ 1,  1,  2],
       [ 0,  5,  2],
       [-1,  3,  1]])

In [7]:
# a function to add raws
# takes parameters A, k, i, j nad returns an array resulting from 
# adding k times row j to row i

def add_row(A, k, i, j):
    """Add k times row j to to row i in matrix A"""
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i, j] = k
    return E @ A

In [8]:
def scale_row(A, k, i):
    """Multiply row i by k in matrix A"""
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = k
    return E @ A

In [9]:
def switch_rows(A, i, j):
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = 0
    E[j, j] = 0
    E[i, j] = 1
    E[j, i] = 1
    
    return E @ A

In [40]:
# Lets apply our functions to the augmented matrix M I to find the inverse of matrix M
M = np.array([[5,4,2], [-1,2,1], [1,1,1]])
A = np.hstack([M, np.eye(3)])
A

array([[ 5.,  4.,  2.,  1.,  0.,  0.],
       [-1.,  2.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  1.]])

In [42]:
A1 = switch_rows(A, 0, 2)
A1

array([[ 1.,  1.,  1.,  0.,  0.,  1.],
       [-1.,  2.,  1.,  0.,  1.,  0.],
       [ 5.,  4.,  2.,  1.,  0.,  0.]])

In [47]:
A2 = add_row(A1, 1, 1, 0)
A2

array([[1., 1., 1., 0., 0., 1.],
       [0., 3., 2., 0., 1., 1.],
       [5., 4., 2., 1., 0., 0.]])

In [48]:
A3 = add_row(A2, -5, 2, 0)
A3

array([[ 1.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  3.,  2.,  0.,  1.,  1.],
       [ 0., -1., -3.,  1.,  0., -5.]])

In [50]:
A4 = switch_rows(A3, 1, 2)
A4

array([[ 1.,  1.,  1.,  0.,  0.,  1.],
       [ 0., -1., -3.,  1.,  0., -5.],
       [ 0.,  3.,  2.,  0.,  1.,  1.]])

In [53]:
A5 = scale_row(A4, -1, 1)
A5

array([[ 1.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  3., -1.,  0.,  5.],
       [ 0.,  3.,  2.,  0.,  1.,  1.]])

In [54]:
A6 = add_row(A5, -3, 2, 1)
A6

array([[  1.,   1.,   1.,   0.,   0.,   1.],
       [  0.,   1.,   3.,  -1.,   0.,   5.],
       [  0.,   0.,  -7.,   3.,   1., -14.]])

In [55]:
A7 = scale_row(A6, -1/7, 2)
A7

array([[ 1.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.        ,  1.        ,  3.        , -1.        ,  0.        ,
         5.        ],
       [ 0.        ,  0.        ,  1.        , -0.42857143, -0.14285714,
         2.        ]])

In [57]:
A8 = add_row(A7, -3, 1, 2)
A8

array([[ 1.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.        ,  1.        ,  0.        ,  0.28571429,  0.42857143,
        -1.        ],
       [ 0.        ,  0.        ,  1.        , -0.42857143, -0.14285714,
         2.        ]])

In [62]:
A9 = add_row(A8, -1, 0, 2)
A9

array([[ 1.        ,  1.        ,  0.        ,  0.42857143,  0.14285714,
        -1.        ],
       [ 0.        ,  1.        ,  0.        ,  0.28571429,  0.42857143,
        -1.        ],
       [ 0.        ,  0.        ,  1.        , -0.42857143, -0.14285714,
         2.        ]])

In [63]:
A10 = add_row(A9, -1, 0, 1)
A10

array([[ 1.        ,  0.        ,  0.        ,  0.14285714, -0.28571429,
         0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.28571429,  0.42857143,
        -1.        ],
       [ 0.        ,  0.        ,  1.        , -0.42857143, -0.14285714,
         2.        ]])

In [64]:
# verify
Minv = A10[:,3:]
print(Minv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [68]:
result = Minv @ M
print(np.round(result, 15))

[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]


In [4]:
# Example 2
A = np.array([[6, 15, 1], [8, 7, 12], [2, 7, 8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [5]:
b = np.array([[2], [14], [10]])
print(b)

[[ 2]
 [14]
 [10]]


In [6]:
# form an augmented matrix M
M = np.hstack([A, b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


In [13]:
M1 = scale_row(M, 1/6, 0)
print(M1)

array([[ 1.        ,  2.5       ,  0.16666667,  0.33333333],
       [ 8.        ,  7.        , 12.        , 14.        ],
       [ 2.        ,  7.        ,  8.        , 10.        ]])

In [14]:
M2 = add_row(M1, -8, 1, 0)
print(M2)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [16]:
M3 = add_row(M2, -2, 2, 0)
print(M3)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [17]:
M4 = scale_row(M3, -1/13, 1)
print(M4)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]


In [19]:
M5 = add_row(M4, -2, 2, 1)
print(M5)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          9.30769231 11.07692308]]


In [20]:
M6 = scale_row(M5, 1/M5[2,2], 2)
M6

array([[ 1.        ,  2.5       ,  0.16666667,  0.33333333],
       [ 0.        ,  1.        , -0.82051282, -0.87179487],
       [ 0.        ,  0.        ,  1.        ,  1.19008264]])

In [21]:
M7 = add_row(M6, -M6[1,2], 1, 2)
M7

array([[1.        , 2.5       , 0.16666667, 0.33333333],
       [0.        , 1.        , 0.        , 0.1046832 ],
       [0.        , 0.        , 1.        , 1.19008264]])

In [26]:
M8 = add_row(M7, -M7[0, 2], 0, 2)
print(M8)

[[1.         2.5        0.         0.13498623]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [27]:
M9 = add_row(M8, -M8[0, 1], 0, 1)
M9

array([[ 1.        ,  0.        ,  0.        , -0.12672176],
       [ 0.        ,  1.        ,  0.        ,  0.1046832 ],
       [ 0.        ,  0.        ,  1.        ,  1.19008264]])

In [29]:
# the solution of Ax = b is
x = M9[:,3].reshape(3, 1)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [32]:
x = la.solve(A, b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]
